In [56]:
import pandas as pd

In [57]:
df=pd.read_csv("netflix_customer_churn.csv")

In [58]:
df.head(4)

,customer_id,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,a9b75100-82a8-427a-a208-72f24052884a,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror

In [59]:
df.shape

(5000, 14)

In [60]:
df.columns

Index(['customer_id', 'age', 'gender', 'subscription_type', 'watch_hours',
       'last_login_days', 'region', 'device', 'monthly_fee', 'churned',
       'payment_method', 'number_of_profiles', 'avg_watch_time_per_day',
       'favorite_genre'],
      dtype='object')

In [61]:
df = df.drop(columns=['customer_id'])

In [ ]:
from matplotlib import pyplot as plt

In [64]:
df.columns

Index(['age', 'gender', 'subscription_type', 'watch_hours', 'last_login_days',
       'region', 'device', 'monthly_fee', 'churned', 'payment_method',
       'number_of_profiles', 'avg_watch_time_per_day', 'favorite_genre'],
      dtype='object')

In [9]:
df.dtypes

age                         int64
gender                     object
subscription_type          object
watch_hours               float64
last_login_days             int64
region                     object
device                     object
monthly_fee               float64
churned                     int64
payment_method             object
number_of_profiles          int64
avg_watch_time_per_day    float64
favorite_genre             object
dtype: object

In [10]:
df.isnull().sum()

age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [11]:
df.head(4)

,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror

In [14]:
df['subscription_type'].unique()

array(['Basic', 'Standard', 'Premium'], dtype=object)

In [15]:
df.dtypes

age                         int64
gender                     object
subscription_type          object
watch_hours               float64
last_login_days             int64
region                     object
device                     object
monthly_fee               float64
churned                     int64
payment_method             object
number_of_profiles          int64
avg_watch_time_per_day    float64
favorite_genre             object
dtype: object

In [17]:
df['region'].unique()

array(['Africa', 'Europe', 'Asia', 'Oceania', 'South America',
       'North America'], dtype=object)

| Encoding Technique     | When to Use                                                      | Example Data                          | Encoded Output Example                            |
| ---------------------- | ---------------------------------------------------------------- | ------------------------------------- | ------------------------------------------------- |
| **Label Encoding**     | When data has **order (ordinal)** and simple mapping is fine     | Size: Small, Medium, Large            | Small → 0, Medium → 1, Large → 2                  |
| **Ordinal Encoding**   | When data has **clear ranking** and you want control over values | Plan: Basic, Standard, Premium        | Basic → 0, Standard → 1, Premium → 2              |
| **One-Hot Encoding**   | When data has **no order (nominal)** and few categories          | City: Pune, Mumbai, Delhi             | Pune → [1,0,0], Mumbai → [0,1,0], Delhi → [0,0,1] |
| **Binary Encoding**    | When **many categories** and want fewer columns                  | Category: A, B, C, D                  | A → 00, B → 01, C → 10, D → 11                    |
| **Frequency Encoding** | When category importance depends on **count**                    | City frequency: Mumbai(100), Pune(50) | Mumbai → 100, Pune → 50                           |
| **Target Encoding**    | When large data & want encoding based on **target variable**     | City vs Salary                        | Mumbai → 50000, Pune → 30000                      |
| **Hash Encoding**      | When **very high cardinality** and memory matters                | User IDs                              | ID → hashed number (fixed columns)                |

In [18]:
df['gender'].unique()

array(['Other', 'Female', 'Male'], dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

lb.fit_transform(df['gender'])

array([2, 2, 0, ..., 1, 0, 1])

In [26]:

df['gender'] = lb.fit_transform(df['gender'])
df['subscription_type'] = lb.fit_transform(df['subscription_type'])

In [27]:
df.head(4)

,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,51,2,0,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,47,2,2,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,27,0,2,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,53,2,1,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror

In [33]:
lb = LabelEncoder()
df['subscription_type'] = lb.fit_transform(df['subscription_type'])

print(lb.classes_)
lb.classes_

[0 1 2]

array([0, 1, 2])

In [31]:
mapping = dict(zip(lb.classes_, lb.transform(lb.classes_)))
print(mapping)

{0: 0, 1: 1, 2: 2}

In [34]:
df.dtypes

age                         int64
gender                      int64
subscription_type           int64
watch_hours               float64
last_login_days             int64
region                     object
device                     object
monthly_fee               float64
churned                     int64
payment_method             object
number_of_profiles          int64
avg_watch_time_per_day    float64
favorite_genre             object
dtype: object

In [35]:
df['region'].unique()

array(['Africa', 'Europe', 'Asia', 'Oceania', 'South America',
       'North America'], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

on = OneHotEncoder(sparse_output=False)

encoded = on.fit_transform(df[['region']])

In [51]:
df['region']=encoded
df['payment_method']=on.fit_transform(df[['payment_method']])
df['device']=on.fit_transform(df[['device']])
df['favorite_genre']=on.fit_transform(df[['favorite_genre']])

In [52]:
df.head()

,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,51,2,2,14.73,29,1.0,1.0,8.99,1,0.0,1,0.49,1.0
1,47,2,2,0.70,19,0.0,1.0,13.99,1,0.0,5,0.03,0.0
2,27,0,0,16.32,10,0.0,1.0,13.99,0,0.0,2,1.48,0.0
3,53,2,2,4.51,12,0.0,1.0,17.99,1,0.0,2,0.35,0.0
4,56,2,2,1.89,13,1.0,1.0,13.99,1,0.0,2,0.13,1.0

In [45]:
df['payment_method'].unique()

array(['Gift Card', 'Crypto', 'Debit Card', 'PayPal', 'Credit Card'],
      dtype=object)

In [ ]:
df['device'].unique()

array(['TV', 'Mobile', 'Laptop', 'Desktop', 'Tablet'], dtype=object)

In [50]:
df['favorite_genre'].unique()

array(['Action', 'Sci-Fi', 'Drama', 'Horror', 'Romance', 'Comedy',
       'Documentary'], dtype=object)

In [53]:
df.dtypes

age                         int64
gender                      int64
subscription_type           int64
watch_hours               float64
last_login_days             int64
region                    float64
device                    float64
monthly_fee               float64
churned                     int64
payment_method            float64
number_of_profiles          int64
avg_watch_time_per_day    float64
favorite_genre            float64
dtype: object

In [55]:
df[:10]

,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,51,2,2,14.73,29,1.0,1.0,8.99,1,0.0,1,0.49,1.0
1,47,2,2,0.70,19,0.0,1.0,13.99,1,0.0,5,0.03,0.0
2,27,0,0,16.32,10,0.0,1.0,13.99,0,0.0,2,1.48,0.0
3,53,2,2,4.51,12,0.0,1.0,17.99,1,0.0,2,0.35,0.0
4,56,2,2,1.89,13,1.0,1.0,13.99,1,0.0,2,0.13,1.0
5,58,0,0,13.80,26,0.0,1.0,13.99,0,0.0,3,0.51,1.0
6,48,2,2,13.83,20,0.0,1.0,8.99,0,0.0,5,0.66,0.0
7,51,1,1,14.30,56,0.0,1.0,8.99,1,0.0,1,0.25,1.0
8,45,2,2,9.98,10,0.0,1.0,8.99,0,0.0,3,0.91,0.0
9,32,2,2,2.22,34,0.0,1.0,17.99,1,0.0,1,0.06,0.0